version: '3.8'
services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    volumes:
      - ./data/mongodb:/data/db
 fansite:
    image: docker.pkg.github.com/madsadfatcat/genesyx-fansite/genesyx-fansite:latest
    container_name: fansite
    restart: always
    volumes:
      - .env:/app/.env
    ports:
      - 3000:3000
